[project]
name = "linear-canonical-transform"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Alok Singh", email = "alokbeniwal@gmail.com" }
]
dependencies = [
    "jax>=0.4.31",
    "jaxtyping>=0.2.34",
    "beartype>=0.18.5",
    "einops>=0.8.0",
    "hypothesis>=6.112.1",
    "jaxlib>=0.4.31",
    "tyro>=0.8.10",
    "ipykernel>=6.29.5",
    "matplotlib>=3.9.2",
    "plotly>=5.24.1",
    "numpy>=2.1.1",
    "scipy>=1.14.1",
    "pytest",
    "hypothesis",
]
readme = "README.md"
requires-python = ">= 3.12"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = [
    "pytest>=8.3.3",
    "hypothesis>=6.118.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/linear_canonical_transform"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --hypothesis-show-statistics"
