"""Compatibility exports for the older package name."""

from lct_activation import (
    DiscretizationMode,
    DoctorCheck,
    DoctorReport,
    LCTActivation,
    LCTLayer,
    LCTLinear,
    LCTModReLU,
    NormMode,
    canonical_determinant,
    chirpz_lct,
    compose_canonical,
    composition_error,
    finite_lct_matrix,
    format_doctor_text,
    linear_canonical_transform,
    property_report,
    relative_frobenius_error,
    run_doctor,
    spectral_fractional_fourier_matrix,
    spectral_fractional_fourier_transform,
    symplectic_d,
    unitarity_error,
)

__all__ = [
    "NormMode",
    "DiscretizationMode",
    "DoctorCheck",
    "DoctorReport",
    "LCTActivation",
    "LCTLayer",
    "LCTLinear",
    "LCTModReLU",
    "canonical_determinant",
    "chirpz_lct",
    "compose_canonical",
    "composition_error",
    "finite_lct_matrix",
    "format_doctor_text",
    "linear_canonical_transform",
    "property_report",
    "relative_frobenius_error",
    "run_doctor",
    "spectral_fractional_fourier_matrix",
    "spectral_fractional_fourier_transform",
    "symplectic_d",
    "unitarity_error",
]
